### ISSUE TITLE
Can I use your code to frontalize other face dataset? If yes, can you tell me how? thx

### ISSUE THREAD

**Issue by Suguanning** [csyxwei/FFWM#10]

**Comment by csyxwei** [comment]
### Prepare your dataset

You should refer to the `README` in data_process to prepare your dataset, and organise your data as follow:

```
dataset
  └── your_dataset_name
          └── images
```

### Download pretrained models

Download the models from [GoogleDrive](https://drive.google.com/drive/folders/1U26FvuLtXraxPrRNxCxFka3DOvRuG4NW?usp=sharing) or [BaiduNetDisk](https://pan.baidu.com/s/1X62Atd9Q_USs0aGQk3WllA) (l98p) to ./checkpoints folder. The models are structured as follows:

```
    ./checkpoints
          ├── ffwm
          │       ├── latest_net_flowNetF.pth
          │       └── latest_net_netG.pth
          ├── lightCNN_10_checkpoint.pth (pretrained)
          └── LightCNN_29Layers_checkpoint.pth (original)
```

### Test your dataset

```python
python test_ffwm.py \
                --datamode your_dataset_name \
                --dataroot path/to/dataset \
                --lightcnn path/to/pretrained lightcnn 
```

**Comment by Masterzhuior** [comment]
I have also used the model on the celeba dataset, and all the images have not changed.

**Comment by Suguanning** [comment]
> Thank you for your last reply. But I encountered another problem. Why does the picture not change at all when I use your trained model to frontalize the celeba dataset.

Thank you for your last reply. But I encountered another problem. Why does the picture not change at all when I use your trained model to frontalize the celeba dataset.

**Comment by Suguanning** [comment]
> ### Prepare your dataset
> You should refer to the `README` in data_process to prepare your dataset, and organise your data as follow:
> 
> ```
> dataset
>   └── your_dataset_name
>           └── images
> ```
> 
> ### Download pretrained models
> Download the models from [GoogleDrive](https://drive.google.com/drive/folders/1U26FvuLtXraxPrRNxCxFka3DOvRuG4NW?usp=sharing) or [BaiduNetDisk](https://pan.baidu.com/s/1X62Atd9Q_USs0aGQk3WllA) (l98p) to ./checkpoints folder. The models are structured as follows:
> 
> ```
>     ./checkpoints
>           ├── ffwm
>           │       ├── latest_net_flowNetF.pth
>           │       └── latest_net_netG.pth
>           ├── lightCNN_10_checkpoint.pth (pretrained)
>           └── LightCNN_29Layers_checkpoint.pth (original)
> ```
> 
> ### Test your dataset
> ```python
> python test_ffwm.py \
>                 --datamode your_dataset_name \
>                 --dataroot path/to/dataset \
>                 --lightcnn path/to/pretrained lightcnn 
> ```
Thanks for your last reply. But I encountered another problem.Why does the picture not change at all when I use your trained model to frontalize the celeba dataset

**Comment by Masterzhuior** [comment]
> ### Prepare your dataset
> You should refer to the `README` in data_process to prepare your dataset, and organise your data as follow:
> 
> ```
> dataset
>   └── your_dataset_name
>           └── images
> ```
> 
> ### Download pretrained models
> Download the models from [GoogleDrive](https://drive.google.com/drive/folders/1U26FvuLtXraxPrRNxCxFka3DOvRuG4NW?usp=sharing) or [BaiduNetDisk](https://pan.baidu.com/s/1X62Atd9Q_USs0aGQk3WllA) (l98p) to ./checkpoints folder. The models are structured as follows:
> 
> ```
>     ./checkpoints
>           ├── ffwm
>           │       ├── latest_net_flowNetF.pth
>           │       └── latest_net_netG.pth
>           ├── lightCNN_10_checkpoint.pth (pretrained)
>           └── LightCNN_29Layers_checkpoint.pth (original)
> ```
> 
> ### Test your dataset
> ```python
> python test_ffwm.py \
>                 --datamode your_dataset_name \
>                 --dataroot path/to/dataset \
>                 --lightcnn path/to/pretrained lightcnn 
> ```

Like him, I used the model to process celeba data sets, but it didn't work at all

**Comment by csyxwei** [comment]
Hi, could you provide your test results? FFWM is trained on MultiPIE dataset, which is collected in controlled setting, while CelebA is a chanllage in-the-wild dataset. So it may not obtained expected results on CelebA.

**Comment by Suguanning** [comment]
> Hi, could you provide your test results? FFWM is trained on MultiPIE dataset, which is collected in controlled setting, while CelebA is a chanllage in-the-wild dataset. So it may not obtained expected results on CelebA.

Thanks again. I have sent my test results to your e-mail.

**Comment by WengRan** [comment]
> > Hi, could you provide your test results? FFWM is trained on MultiPIE dataset, which is collected in controlled setting, while CelebA is a chanllage in-the-wild dataset. So it may not obtained expected results on CelebA.
> 
> Thanks again. I have sent my test results to your e-mail.

Do you solve this problem? I face the same issue, could you help me? thanks!
