### ISSUE TITLE
finetune.py: error: unrecognized arguments: 

### ISSUE THREAD

**Issue by xhlho** [csyxwei/FFWM#15]
```
python finetune.py \
            --save_path ../checkpoints/ \
            --dataroot path/to/dataset/multipie \
            --model_path path/to/original lightcnn \
            --preload
```
这几个分别需要我们填什么路径进去啊

**Comment by csyxwei** [comment]
`dataroot`是multipie数据集的路径，`model_path`是原始LightCNN的路径，对应到下图的模型：
<img width="524" alt="image" src="https://user-images.githubusercontent.com/23421814/231682208-7d811937-703c-4286-8e9f-f29944265a34.png">

**Comment by xhlho** [comment]
老哥，还有两个呢

**Comment by csyxwei** [comment]
`save_path`是你要存的模型的路径，可以任意指定。
 `--preload `是指要不要将数据都加载到内存里加速训练，带上它是指要提前将数据加载到内存里，去掉就是不加载。
