### ISSUE TITLE
flownet training problem

### ISSUE THREAD

**Issue by xieyipeng** [csyxwei/FFWM#5]
Hi, Do you use MultiPIE dataset to train the flow field network?

**Comment by xieyipeng** [comment]
![image](https://user-images.githubusercontent.com/32957035/133980543-c394d182-165f-4e55-b9a6-8ec682bb98f3.png)

And I don't know what the parameters in the picture above mean....
Looking forward to your answer.

**Comment by csyxwei** [comment]
Hi, yes, I used MultiPIE dataset to train the  Forward FlowNet and Backward FlowNet.

`_S`  suffix means the profile images and `_F` suffix means the corresponding frontal images. `img` prefix means the training images,  `lm` prefix means the landmarks and `mask` prefix means the mask images. `gate` is a mask used to filter invalid landmarks. It is a 0/1 tensor and 1 means the landmarks in `lm_S` and `lm_F` are valid.

**Comment by xieyipeng** [comment]
> Hi, yes, I used MultiPIE dataset to train the Forward FlowNet and Backward FlowNet.
> 
> `_S` suffix means the profile images and `_F` suffix means the corresponding frontal images. `img` prefix means the training images, `lm` prefix means the landmarks and `mask` prefix means the mask images. `gate` is a mask used to filter invalid landmarks. It is a 0/1 tensor and 1 means the landmarks in `lm_S` and `lm_F` are valid.

Thank you for your answer, I've learned.

**Comment by xieyipeng** [comment]
> Hi, yes, I used MultiPIE dataset to train the Forward FlowNet and Backward FlowNet.
> 
> `_S` suffix means the profile images and `_F` suffix means the corresponding frontal images. `img` prefix means the training images, `lm` prefix means the landmarks and `mask` prefix means the mask images. `gate` is a mask used to filter invalid landmarks. It is a 0/1 tensor and 1 means the landmarks in `lm_S` and `lm_F` are valid.

Bother again, what is the difference between `gate` and Landmark `lm_S` or `lm_F`?

**Comment by csyxwei** [comment]
`lm_S` is the profile image landmarks and `lm_F` is the frontal image landmarks. 

According to the paper suppl:

> We move face contour landmarks in the vertical and horizontal directions and mark new landmarks and correspondences in the above areas between <img src="https://latex.codecogs.com/gif.latex?I " />  (img_S) and <img src="https://latex.codecogs.com/gif.latex?I^{gt}" /> (img_F).

Due to there are some landmarks are moved to the background area, so we use the mask and landmarks to create a `gate` to filter these out-of-bounds landmarks. Besides, when the face pose is large, most of the landmarks corresponding to the occluded face part are inaccurate, so we also use the `gate` to filter these landmarks.

You can see [this part code](https://github.com/csyxwei/FFWM/blob/d42c578cabe1b81c6b1bb0c3cb707b190fca3c68/data_process/process.py#L314) and [this part code](https://github.com/csyxwei/FFWM/blob/d42c578cabe1b81c6b1bb0c3cb707b190fca3c68/data_process/process.py#L315) for more details.

**Comment by xieyipeng** [comment]
By the way, how is the `rank-1` recognition rate calculated?

Is it like this?

I have a test set, `T`, which contains both front and profile image. data size is `N`.

Take an example from profile data, as `T_profile_x`, Input `T_profile_x` into the trained model, get the Frontalization results `T_profile_x_fake`,

And then some feature extraction method is used to extract `T_profile_x_fake` feature vectors, as `x_fake_feature`. 

finally, extract all image feature vectors in the front face data set, as `all_feature_list`, Compare the distance between `x_fake_feature` and `all_feature_list` one by one. If the face `temp` have the smallest distance corresponds to the input, and x is `temp`, then set `score+1`. 

Repeat the above steps...

Get the final score `S`, and `S/N` is `rank-1` score?

I'm not a native English speaker, sorry. 

Thank you very much!

**Comment by csyxwei** [comment]
Yeah, you are right, it is how we calculate the rank-1 recognition accuracy. 

The `front face data set` (a.k.a gallery dataset) contains one frontal image for each people, and `LightCNN29` is used as the feature extractor. 

You can see the `AverageMeter` in [`util.py`](https://github.com/csyxwei/FFWM/blob/d42c578cabe1b81c6b1bb0c3cb707b190fca3c68/util/util.py#L141) and test code in [test.py](https://github.com/csyxwei/FFWM/blob/d42c578cabe1b81c6b1bb0c3cb707b190fca3c68/test_ffwm.py#L67) for more details.

**Comment by xieyipeng** [comment]
Another, How do I save the flow field as a picture?

The size is `2*128*128`, channel is `2`

**Comment by xieyipeng** [comment]
Another question: 

How do you perform face alignment? 
Is it to use affine transformation after detecting the key points of the face?

thank u!

**Comment by csyxwei** [comment]
Hi,

Yes, you can refer to issue #3 to see how to extract facial landmarks and align your images.
